duckduckgo/content-blocking-whitelist

- trackers-whitelist.txt
Added fixes for: 
- Ebay.ca
- BelairDirect
- Apple Store
> Whitelist Adobe, Apple, and Ebay assets

- trackers-whitelist.txt
http://store.vmware.com/store/vmware/html/pbPage.fusion-vs-parallels?src=WWW_eBIZ_productpage_Fusion_Parallels_US
Also adds GitHub Images, so you can see the image below ;)
> Whitelist DigitalRiver img subdomain

- trackers-whitelist.txt
Adds `global.fncstatic.com` to whitelist to fix videos:
e.g. http://video.foxnews.com/v/5644525328001/?#sp=news-clips
> Whitelist: global.fncstatic.com to fix foxnews videos

- trackers-whitelist.txt
Our abp module is over matching on some regex entries. This one is particularly bad. 
Some test sites that are currently broken:
http://urbanartassociation.com/
http://thepioneerwoman.com/cooking/
> whitelist over matching regex

- trackers-whitelist.txt
The back slashes shouldn't be escaped. Not sure how that happened.
> fix whitelist entry

- trackers-whitelist-temporary.txt
- trackers-whitelist.txt
Remove nytimes.com from temp whitelist and whitelist individual tracker.
> fix nytimes

- trackers-whitelist.txt
Reported on [reddit](https://www.reddit.com/r/duckduckgo/comments/7mn3pk/ddg_firefox_addon_not_compatible_with_xhamster/)
Looks like an abp parser bug that I'll need to spend more time looking into so I'll add these to the whitelist for now.
> xhcdn whitelist

- trackers-whitelist-temporary.txt
From user feedback- 
"----URL is https://www.calbanktrust.com/
I would love to keep this extension installed, but I cannot access my company bank account. It will not allow login, despite having whitelisted all of the visible sites shown on the way through user login."
> whitelist calbanktrust

- trackers-whitelist.txt
Does the following:
- don't count `s3.amazonaws.com` as a tracker (it's used as a CDN e.g. here: https://www.vuoriclothing.com/ - nothing visually breaks, but the console gives JS errors)
- don't count Polldaddy polls as a tracker (we didn't have a sample site, but I found this: http://snippets.wikidot.com/code:polldaddy - scroll down to "in action")
- fix canadatyres.ca - without this whitelist entry, the following page refreshes every 5-10 seconds: http://www.canadiantire.ca/en/pdp/rust-oleum-stone-effects-step-3-counter-top-coating-0490270p.html#Reviews
> Add three sites to the whitelist

- trackers-whitelist.txt
This fixes video playback on abc.go.com.
Before: 
After:
> unblock geolock request on abc

- trackers-whitelist.txt
https://www.bbc.co.uk/iplayer/episode/b09q4f9v/spiral-series-6-episode-10
Before:
After:
> whitelist nav-analytics to fix bbci player.

- trackers-whitelist.txt
We were blocking yahoo on their own page, which isn't the correct behavior. Temporarily whitelisting the request while we update internals to fix.
> don't block first party yahoo request on yahoo domains.

- trackers-whitelist-temporary.txt
Site is no longer broken with privacy protection enabled, so remove it from the temporary whitelist.
> remove business insider from whitelist

- trackers-whitelist.txt
Fix video playback on chefkoch.de. Check https://www.chefkoch.de/video/artikel/1213,0/Chefkoch/Brot-und-Broetchen-backen-und-schleifen.html to see fix.
> whitelist chefkoch cdn on chefkoch.de

- trackers-whitelist.txt
EasyList has some block rules that are overly wide and blocking all third party content on arbitrary websites (see https://github.com/easylist/easylist/blob/master/easylist/easylist_specific_block.txt#L5509).
A lot of these websites are using embedded youtube videos, which are broken by the above rule. This PR unbreaks embedded youtube videos.
> fix youtube embedded players blocked by wide easylist rules

- trackers-whitelist-temporary.txt
This was actually solved by https://github.com/duckduckgo/abp-filter-parser/pull/4.
In order to see locally, make sure to `npm update abp-filter-parser` followed by `npm install` from within the extension directory to get the latest.
> remove spotify from temporary whitelist

- trackers-whitelist.txt
Live chat was being blocked on a handful of sites, including capital one and best buy. This unblocks it.
capital one before: 
capital one after:
more info on best buy here: https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt#L813
> unblock 247 live chat

- trackers-whitelist.txt
> whitelist pixel on spiegel.de to prevent adblock warning.

- trackers-whitelist.txt
We were blocking a request to amazon that caused a ton of streaming sites to detect adblock usage and tell you to turn off adblock. There seems to be a streaming framework that a lot of sites are using (at least all sites on A+E networks) that uses this same method of detection, so I didn't limit the rule to a specific list of sites.
To test, try watching one of the following videos:
https://www.history.com/shows/swamp-people/season-9/episode-11
https://www.mylifetime.com/shows/glam-masters/season-1/episode-7
Before:
After:
> fix adblock warning on history.com, aetv.com, mylifetime.com, etc

- trackers-whitelist.txt
We were identifying list-manage.com domain as mailchimp and blocking request to it. This was causing newsletter sign up forms to break. This whitelists the subscription path and unbreaks those forms.
I've been using the form found at the bottom of a-d-o.com to test.
> Fix mailchimp newsletter sign up forms

- trackers-whitelist.txt
URL is http://tennislink.usta.com/Tournaments/Schedule/Search.aspx
Before fix, clicking search button doesn't do anything. After fix, clicking search button works as expected.
> unbreak search on tennislink.usta.com

- trackers-whitelist.txt
URL is: https://www.delltechnologiesworld.com/live.htm?cmp=dew18_live_promo_dellhp&dgc=IR&cid=dtwaprilbanner&lid=B1&ref=hbn
Before:
After:
> fix delltechnologiesworld.com

- trackers-whitelist.txt
Yandex rule in disconnect list is causing us to block images hosted on yandex's cdn (img-fotki.yandex.ru). Seems to be relatively common (https://publicwww.com/websites/%22img-fotki.yandex.ru%22/).
URL is: http://nnm-club.me/
> whitelist yandex image cdn

- trackers-whitelist.txt
Disconnect list is causing us to block all third-party requests to yandex.ru, including maps. This allows embedded yandex maps to function.
URL is: https://chekalskiy.ru/slutsky/
> fix embedded yandex maps

- trackers-whitelist.txt
Blocking the request to 2o7.net was breaking this site.
URL is: https://www.kiplinger.com/
Before: Nothing could be clicked.
After: Site works as it should.
> unbreak kiplinger.com

- trackers-whitelist.txt
Before: site blocked by adblock warning:
After: site usable:
> Avoid adblock wall on aftonbladet.se

- trackers-whitelist.txt
A lot of sites use default stylesheets and scripts for their embedded google maps. These are hosted on developers.google.com. A couple of example requests:
`https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js`
`https://developers.google.com/maps/documentation/javascript/examples/default.css?csw=1`
Others may be found at: https://publicwww.com/websites/%22https%3A%2F%2Fdevelopers.google.com%2Fmaps%2Fdocumentation%2Fjavascript%2F%22/.
This simply allows those request to go through.
> unbreak sites with maps hosted on developers.google.com

- trackers-whitelist.txt
~30k sites use embedded contact forms from marketo: https://publicwww.com/websites/marketo.com%2Fjs%2Fforms2%2Fjs%2Fforms2.min.js/
First two rules allow form to load, second two rules allow form to be submitted.
URL is: https://www.appannie.com/en/landing/contact-sales/
Another one to test is: https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos (safari only)
Before:
After:
> whitelist necessary requests to fix embedded marketo forms

- trackers-whitelist-temporary.txt
Many online banking portals use fingerprinting techniques to help with fraud detection. These sites are difficult if not impossible to debug without valid logins. Add list of sites reported broken to temporary whitelist while we decide on a strategy moving forward.
To test, visit a site on the list and check that it is whitelisted.
> whitelist bank sites that have been reported to have broken logins

- trackers-whitelist.txt
This site is making multiple requests to fetch gpt.js, and our surrogate response is breaking the radio stream (in safari only!). Whitelist gpt request on site to fix radio stream.
URL is: http://ijpr.org/post/oregon-legislature-approves-gov-kate-browns-tax-break-business
> Fix audio stream on ijpr.org

- trackers-whitelist.txt
richmedia.channeladvisor.com/.. seems to be used by a lot of ecommerce sites. We'd previously whitelisted their image cdn to fix bjs.com. This rule allows the associated gallery script.
URL is: https://www.costco.com/LG-6.3CuFt-INDUCTION-Slide-in-Range-with-ProBake-Convection.product.100341932.html
Before:
After:
> unblock other channeladvisor image gallery script

- trackers-whitelist-temporary.txt
Received feedback that capitalone.ca is breaking, so adding to list of whitelisted bank sites.
> add capitalone.ca to temp whitelist

- trackers-whitelist-temporary.txt
As previously mentioned, we are whitelisting banking websites for which we have received breakage reports because they use legitimate fingerprinting to verify users' authenticity. This PR simply adds td.com to the list of sites where we do not block this type of activity.
> Add td to list of whitelisted bank sites

- trackers-whitelist.txt
This just anchors the manually added unanchored rules we previously added to ensure rogue trackers can't spoof their domains in their urls and bypass our protection. This shouldn't change functionality at all.
> anchor unanchored rules

- trackers-whitelist.txt
Review: @jdorweiler 
Site fixes contained in this PR:
- unblock intercom.io globally
- unblock doubleclick.net/ddm/$image globally (commonly used as anti-adblock bait)
- https://redballoon.com.au entire site
- https://investing.com adblock wall
- https://spiegel.de adblock wall
- https://www.tracfone.com/techsupport support chat
- https://www.etonline.com/media/video/a_timeline_of_ben_affleck_alcohol_addled_past-213017
- https://thechive.com/2018/08/27/monday-hits-me-right-in-the-fails-2/ video stream
- https://whalesrule.tumblr.com/ entire site
- https://payment.mercuryinsurance.com/payments/stateSelection broken form
- http://www.nba.com/video/2018/08/09/lebron-james-first-laker-workout video stream
- https://www.dunesvillage.com/reservations/?checkin=09%2F01%2F2018&checkout=09%2F02%2F20 …
> Fix handful of sites, tighten up whitelist rule for apstag.js, unblock embedded salesforce assets

- trackers-whitelist-temporary.txt
I went through and tested the remaining items on the temporary whitelist that aren't banks. Looks like all of them are fully functional now, so I'm removing them from the temporary whitelist.
> remove sites from temporary whitelist that are no longer issues.

- trackers-whitelist.txt
A lot of email services such as protonmail load remote images in emails, unlike gmail which creates their own cached version. We're erroneously blocking mailchimp images due to us identifying mailchimp as a tracker. This just whitelists the path they use to serve images embedded in emails.
Before: 
After:
> unblock embedded mailchimp images

- trackers-whitelist-temporary.txt
There have been some reports of the extension breaking gmail. Adding it to the temp whitelist until we can figure out what's going on.
> add gmail to temp whitelist

- trackers-whitelist-temporary.txt
We've seen enough reports for this domain that we're whitelisting it while we figure out what the issue is.
> Temporarily whitelist webmail.earthlink.net

- trackers-whitelist.txt
Was breaking game version selector on https://fallout.bethesda.net/games/fallout-76.
> expand whitelisting gtm on bethesda.net

- trackers-whitelist-temporary.txt
Fix is on the way, just needs 12 hrs to propagate
> Add earthlink back to temp whitelist

- trackers-whitelist-temporary.txt
Hoping the https change we made fixes the site.
> Remove earthlink webmail from temp whitelist

- trackers-whitelist.txt
surrogate for gpt.js wasn't good enough. temporarily whitelisting gpt on gizmodo sites to fix them while we work on our own surrogates.
To test, visit https://adequateman.deadspin.com/down-with-big-scooter-1830559154 and scroll down to the comments section. They should load properly now.
> Fix gizmodo comment sections

- trackers-whitelist.txt
To test, try a few videos:
https://video.foxnews.com/v/6028688814001/#sp=show-clips
https://video.foxbusiness.com/v/6028724742001/#sp=show-clips
They should load now
> Fix video streaming on foxnews

- trackers-whitelist-temporary.txt
Confirmed that all of these domains are either fixed now or are wontfix issues (eg paywalls).
> Remove temp whitelist rules that are no longer necessary

- trackers-whitelist-temporary.txt
Blocking Freewheel is breaking these games. Will remove this once actual fix goes out.
> Temporarily add exception for zone.msn.com to unbreak games
